USE Guia1_1_Ejercicio1_Schumacher_db

GO

DROP TABLE IF EXISTS Alumnos

GO

CREATE TABLE Alumnos
(
	Id INT PRIMARY KEY IDENTITY(1,1),
	Lu INT NOT NULL UNIQUE,
	Nombre VARCHAR(100) NOT NULL,
	Nota DECIMAL(18,2) NOT NULL DEFAULT 0
)